# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(default=1, max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
                ('city_name', models.CharField(max_length=6)),
                ('send_sms_time', models.CharField(max_length=10)),
            ],
        ),
    ]
